const data = {
  name: '',
  street: '',
  city: '',
  zip: '',
  state: '',
  location: '',
  projectDescription: '',
  // starttime: "2.3",
  // endtime: "2.3",
  createdby: '',
  lastupdate: '',
  estimatestart: '',
  estimatend: '',
  users: [],
  pendingRegistrations: [],
  lat: '',
  lng: '',
  flag: false,
  viewUser: [],
  isOpen: false,
}
export default data
